#!/usr/bin/python3
import sys, getopt
import urllib.request, urllib.parse, urllib.error
import json
import collections
import os.path
import time
import logging

USAGE = "\nThe script calculates domain and domain combination prevalences in genomes using as input the results generated by the process_MiST_TCS.py script. \n" + \
	"It calculates also this information at the domain superfamily level for the MiST signal transduction domains. \n\n" + \
	"python " + sys.argv[0] + '''
	-h || --help               - help
	-i || --ifile              - input file 1 (protein and domain information file generated by the process_MiST_TCS.py script)
	-s || --sfile              - input file 2 (with MiST domain information)
	-f || --ffile              - output file 1 (domain prevalence)
	-g || --gfile              - output file 2 (domain combination prevalence)
	-k || --kfile              - output file 3 (domain supefamily prevalence)
	-l || --lfile              - output file 4 (domain supefamily combination prevalence)
'''
# Variables controlled by the script parameters
INPUT_FILE1 = None
INPUT_FILE2 = None
OUTPUT_FILE1 = "genome_to_domain_data.tsv"
OUTPUT_FILE2 = "genome_to_domain_comb_data.tsv"
OUTPUT_FILE3 = "genome_to_superfamily_data.tsv"
OUTPUT_FILE4 = "genome_to_superfamily_comb_data.tsv"

MIST_DOMAIN_TO_SUPERFAMILY = {}
HIS_KINASE_DIM_DOMAINS = ["HisKA", "HisKA_2", "HisKA_3", "H-kinase_dim", "His_kinase"]
HIS_KINASE_CATAL_DOMAINS = ["HATPase_c", "HATPase_c_2", "HATPase_c_5", "HWE_HK"]
RESPONSE_REG_DOMAINS = ["Response_reg", "FleQ"]

# Variables set within the script
LOGGER = logging.getLogger(__name__)
logging.basicConfig(filename=sys.argv[0].replace(".py", "") + "_log.txt", level=logging.INFO)

def initialize(argv):
	global INPUT_FILE1, INPUT_FILE2, OUTPUT_FILE1, OUTPUT_FILE2, OUTPUT_FILE3, OUTPUT_FILE4
	try:
		opts, args = getopt.getopt(argv[1:],"hi:s:f:g:k:l:",["help", "ifile=", "sfile=", "ffile=", "gfile=", "kfile=", "lfile="])
		if len(opts) == 0:
			raise getopt.GetoptError("Options are required\n")
	except getopt.GetoptError as e:
		print("===========ERROR==========\n " + str(e) + USAGE)
		sys.exit(2)
	try:
		for opt, arg in opts:
			if opt in ("-h", "--help"):
				print(USAGE)
				sys.exit()
			elif opt in ("-i", "--ifile"):
				INPUT_FILE1 = str(arg).strip()
			elif opt in ("-s", "--sfile"):
				INPUT_FILE2 = str(arg).strip()
			elif opt in ("-f", "--ffile"):
				OUTPUT_FILE1 = str(arg).strip()
			elif opt in ("-g", "--gfile"):
				OUTPUT_FILE2 = str(arg).strip()
			elif opt in ("-k", "--kfile"):
				OUTPUT_FILE3 = str(arg).strip()
			elif opt in ("-l", "--lfile"):
				OUTPUT_FILE4 = str(arg).strip()
	except Exception as e:
		print("===========ERROR==========\n " + str(e) + USAGE)
		sys.exit(2)

def processInput():
	global MIST_DOMAIN_TO_SUPERFAMILY
	with open(INPUT_FILE2, "r") as iFile2:
		for line in iFile2:
			domain_info = line.split("\t")
			MIST_DOMAIN_TO_SUPERFAMILY[domain_info[2].strip()] = domain_info[3].strip()

# domain_to_protein_count = {"dCache_1":5, "GAF": 2, ...}. This means that in a given genome dCache was found in 5 proteins and GAF in 2 of a considered system.
# This does not count how many times a domain is present in a single protein.
# domain_comb_to_protein_count = {"MEDS,PAS,PAS_3,PAS_4,PAS_9":2}. This means that a particualr domain combiation was found in 2 protins in the given genome
def findDomainAndCombPrevalenceInProteins():
	domain_to_protein_count = collections.defaultdict(int)
	# MiST domain superfamilies only
	superfamily_to_protein_count = collections.defaultdict(int)

	domain_comb_to_protein_count = collections.defaultdict(int)
	# MiST domain superfamilies only
	superfamily_comb_to_protein_count = collections.defaultdict(int)

	Genome_id_prev = None
	with open(INPUT_FILE1, "r") as iFile:
		for protein in iFile:
			# filed 6 has only uniqe domain names with indicated counts showing how many times a given domain is present in a given protein.
			# Domains are sorted alphabetically
			# Ex., HATPase_c:1,HisKA_2:1,MEDS:1,PAS:1,PAS_3:2,PAS_4:1,PAS_9:1 
			protein_record = protein.strip().split("\t")
			Genome_id = protein_record[0]
			domain_counts = protein_record[6].replace("<", "").replace(">", "")
			# if records of a new genome began, save the previous genome data and update variables
			if Genome_id != Genome_id_prev:
				if Genome_id_prev:
					writeToFile(domain_to_protein_count, Genome_id_prev, OUTPUT_FILE1)
					writeToFile(domain_comb_to_protein_count, Genome_id_prev, OUTPUT_FILE2)
					writeToFile(superfamily_to_protein_count, Genome_id_prev, OUTPUT_FILE3)
					writeToFile(superfamily_comb_to_protein_count, Genome_id_prev, OUTPUT_FILE4)

				Genome_id_prev = Genome_id
				domain_to_protein_count = collections.defaultdict(int)
				domain_comb_to_protein_count = collections.defaultdict(int)
				superfamily_to_protein_count = collections.defaultdict(int)
				superfamily_comb_to_protein_count = collections.defaultdict(int)

			domains_and_counts = domain_counts.split(",")
			for domain in domains_and_counts:
				domain = domain.split(":")[0]
				# if entry is a sensor domain
				if domain not in HIS_KINASE_DIM_DOMAINS and domain not in HIS_KINASE_CATAL_DOMAINS:
					domain_to_protein_count[domain]+=1
					if domain in MIST_DOMAIN_TO_SUPERFAMILY:
						superfamily_to_protein_count[MIST_DOMAIN_TO_SUPERFAMILY[domain]]+=1
					else:
						superfamily_to_protein_count[domain]+=1

			# count this domain combination
			domains = sorted(domain_to_protein_count.keys())
			domain_comb_to_protein_count[",".join(domains)]+=1			
			
			# count this superfamily combination
			superfamilies = sorted(superfamily_to_protein_count.keys())
			superfamily_comb_to_protein_count[",".join(superfamilies)]+=1
			
def writeToFile(dataDict, Genome_id_prev, outputFile):
	with open (outputFile, "a") as oFile:
		for element,count in dataDict.items():
			oFile.write("\t".join([Genome_id_prev, element, str(count)]) + "\n")

def main(argv):
	initialize(argv)
	processInput()
	findDomainAndCombPrevalenceInProteins()

main(sys.argv)
