#!/usr/bin/python3
import sys, getopt
import urllib.request, urllib.parse, urllib.error
import json
import collections
import os.path
import time
import logging

USAGE = "\nThe script calculates domain and domain combination prevalences in genomes using as input the results generated by the process_MiST_TCS.py script. \n" + \
	"It calculates also this information at the domain superfamily level for the MiST signal transduction domains. \n\n" + \
	"python " + sys.argv[0] + '''
	-h || --help               - help
	-i || --ifile              - input file 1 (protein and domain statistics information file generated by the analyze_tcs_pergenome.py script, one of four:
	                                * domain prevalence
							        * domain combination prevalence
							        * domain supefamily prevalence
							        * domain supefamily combination prevalence)
	-s || --sfile              - input file 2 (GTDB taxonomy metadata file)
	-f || --ffile              - output file 1 (protein and domains statistics per selected taxon)
	-t || --taxlevel           - taxonomy level to calculate the average at (one of "species", "genus", "order", "family", "class", "phylum", "kingdom")
'''
# Variables controlled by the script parameters
INPUT_FILE1 = None
INPUT_FILE2 = None
INPUT_FILE3 = "/home/vadim/bin/ar53_bac120_taxonmy_r214.tsv"
TAXONOMY_LEVEL = "species"

OUTPUT_FILE1 = "domain_statistics_per_taxon.tsv"

GENOME_TO_DOMAIN = {}
GENOME_TO_TAXONOMY = {}
# Variables set within the script
LOGGER = logging.getLogger(__name__)
logging.basicConfig(filename=sys.argv[0].replace(".py", "") + "_log.txt", level=logging.INFO)

def initialize(argv):
	global INPUT_FILE1, INPUT_FILE2, OUTPUT_FILE1, TAXONOMY_LEVEL
	try:
		opts, args = getopt.getopt(argv[1:],"hi:s:f:t:",["help", "ifile=", "sfile=", "ffile=", "taxlevel="])
		if len(opts) == 0:
			raise getopt.GetoptError("Options are required\n")
	except getopt.GetoptError as e:
		print("===========ERROR==========\n " + str(e) + USAGE)
		sys.exit(2)
	try:
		for opt, arg in opts:
			if opt in ("-h", "--help"):
				print(USAGE)
				sys.exit()
			elif opt in ("-i", "--ifile"):
				INPUT_FILE1 = str(arg).strip()
			elif opt in ("-s", "--sfile"):
				INPUT_FILE2 = str(arg).strip()
			elif opt in ("-f", "--ffile"):
				OUTPUT_FILE1 = str(arg).strip()
			elif opt in ("-t", "--taxlevel"):
				TAXONOMY_LEVEL = tax_level_selector(str(arg).strip())
				if TAXONOMY_LEVEL == None:
					raise Exception("Incorrect argument of -t (--taxlevel) option")
	except Exception as e:
		print("===========ERROR==========\n " + str(e) + USAGE)
		sys.exit(2)

def process_input():
	global GENOME_TO_DOMAIN
	with open(INPUT_FILE1, "r") as iFile1:
		for line in iFile1:
			# domain_s can be a signle domain (GAF_3) or a domain combination (ex, GAF_3,PAS_3,PAS_4,hole)
			genomeID, domain_s, count = line.strip().split("\t")
			GENOME_TO_DOMAIN[genomeID] = (domain_s, count)
	with open(INPUT_FILE3, "r") as iFile3:
		for line in iFile3:
			record = line.strip().split("\t")
			GENOME_TO_TAXONOMY["_".join(record[0].split("_")[1:])] = ";".join(record[1].split(";")[:TAXONOMY_LEVEL])

# reports inofrmation per taxon
# G1 Domcomb2 12
# d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanosarcina;s__Methanosarcina mazei
def process_domains_per_taxon(level):
	for genome, domain_count in GENOME_TO_DOMAIN.items():
		""

def tax_level_selector(level):
	if level is "species":
		return 7
	elif level is "genus":
		return 6
	elif level is "family":
		return 5
	elif level is "order":
		return 4
	elif level is "class":
		return 3
	elif level is "phylum":
		return 2
	elif level is "kingdom":
		return 1
	return None
						
def main(argv):
	initialize(argv)
	process_input()
	process_domains_per_taxon("genus")

main(sys.argv)
