#!/usr/bin/python3
import sys, getopt
import collections

USAGE = "\nThe script calculates domain and domain combination prevalences in genomes using as input the results generated by the obtain_and_process_st.py script. \n" + \
	"It calculates also this information at the domain superfamily level for the MiST signal transduction domains. \n\n" + \
	"python " + sys.argv[0] + '''
	-h || --help               - help
	-d || --dsource            - source database: mistdb (MiST; default) or rmodels (Pfam HMMs with relaxed thresholds) 
	-p || --ptype              - protein type: hk (histidine kinase), rr (reponse regulator), ocp (one-component protein)
	-i || --ifile              - input file 1 (protein and domain information file generated by the obtain_and_process_st.py script)
	-s || --sfile              - input file 2 (with MiST domain information)
	-t || --tfile              - input file 3 (GTDB metadat with genome size and protein counts)
	-f || --ffile              - output file 1 (domain prevalence)
	-g || --gfile              - output file 2 (domain combination prevalence)
	-k || --kfile              - output file 3 (domain supefamily prevalence)
	-l || --lfile              - output file 4 (domain supefamily combination prevalence)
'''
# Variables controlled by the script parameters
SOURCE = "mistdb"
SOURCE_CHOICES = {"mistdb", "rmodels"}
PROTEIN_TYPE = "hk"
PROTEIN_TYPE_CHOICES = {"hk": "Histidine Kinase", "rr": "Response Regulator", "ocp": "One component protein"}
DOMAIN_COMB_TYPES = {"domain": "domain", "domain_comb": "domain_comb", "superfamily": "superfamily", "superfamily_comb": "superfamily_comb"}
INPUT_FILE1 = None
INPUT_FILE2 = None
INPUT_FILE3 = None
OUTPUT_FILE1 = "genome_to_domain_data.tsv"
OUTPUT_FILE2 = "genome_to_domain_comb_data.tsv"
OUTPUT_FILE3 = "genome_to_superfamily_data.tsv"
OUTPUT_FILE4 = "genome_to_superfamily_comb_data.tsv"

# {"genome1": (size, protein_counts), }
# {"genome1": (12463, 1235), }
GENOME_TO_SIZE = {}
MIST_DOMAIN_TO_SUPERFAMILY = {}
HIS_KINASE_DIM_DOMAINS = ["HisKA", "HisKA_2", "HisKA_3", "H-kinase_dim", "His_kinase"]
HIS_KINASE_CATAL_DOMAINS = ["HATPase_c", "HATPase_c_2", "HATPase_c_5", "HWE_HK"]
RESPONSE_REG_DOMAINS = ["Response_reg", "FleQ"]

def initialize(argv):
	global INPUT_FILE1, INPUT_FILE2, INPUT_FILE3, OUTPUT_FILE1, OUTPUT_FILE2, OUTPUT_FILE3, OUTPUT_FILE4, SOURCE, PROTEIN_TYPE
	try:
		opts, args = getopt.getopt(argv[1:],"hd:p:i:s:t:f:g:k:l:",["help", "dsource=", "ptype=", "ifile=", "sfile=", "tfile=", "ffile=", "gfile=", "kfile=", "lfile="])
		if len(opts) == 0:
			raise getopt.GetoptError("Options are required\n")
	except getopt.GetoptError as e:
		print("===========ERROR==========\n " + str(e) + USAGE)
		sys.exit(2)
	try:
		for opt, arg in opts:
			if opt in ("-h", "--help"):
				print(USAGE)
				sys.exit()
			elif opt in ("-d", "--dsource"):
				if str(arg).strip() in SOURCE_CHOICES:
					SOURCE = str(arg).strip()
			elif opt in ("-p", "--ptype"):
				if str(arg).strip() in PROTEIN_TYPE_CHOICES:
					PROTEIN_TYPE = str(arg).strip()
			elif opt in ("-i", "--ifile"):
				INPUT_FILE1 = str(arg).strip()
			elif opt in ("-s", "--sfile"):
				INPUT_FILE2 = str(arg).strip()
			elif opt in ("-t", "--tfile"):
				INPUT_FILE3 = str(arg).strip()
			elif opt in ("-f", "--ffile"):
				OUTPUT_FILE1 = str(arg).strip()
			elif opt in ("-g", "--gfile"):
				OUTPUT_FILE2 = str(arg).strip()
			elif opt in ("-k", "--kfile"):
				OUTPUT_FILE3 = str(arg).strip()
			elif opt in ("-l", "--lfile"):
				OUTPUT_FILE4 = str(arg).strip()
	except Exception as e:
		print("===========ERROR==========\n " + str(e) + USAGE)
		sys.exit(2)

def processInput():
	global MIST_DOMAIN_TO_SUPERFAMILY, GENOME_TO_SIZE
	with open(INPUT_FILE2, "r") as iFile2:
		for line in iFile2:
			domain_info = line.split("\t")
			MIST_DOMAIN_TO_SUPERFAMILY[domain_info[2].strip()] = domain_info[3].strip()
	with open(INPUT_FILE3, "r") as iFile3:
		for line in iFile3:
			#$0 - genome version, $1 - genome accession, $2 - genome size, $3 - protein counts, $4 - GTDB taxonomy, $5 - NCBI taxonomy
			records = line.split("\t")
			if records[0] != "accession":
				GENOME_TO_SIZE[records[0]] = (int(records[2]), int(records[3]))

# domain_to_protein_count = {"dCache_1":5, "GAF": 2, ...}. This means that in a given genome dCache was found in 5 proteins and GAF in 2 of a considered system.
# This does not count how many times a domain is present in a single protein.
# domain_comb_to_protein_count = {"MEDS,PAS,PAS_3,PAS_4,PAS_9":2}. This means that a particualr domain combiation was found in 2 protins in the given genome
# reports inofrmation per genome
def findDomainAndCombPrevalenceInProteins():
	domain_to_protein_count = collections.defaultdict(int)
	# MiST domain superfamilies only
	superfamily_to_protein_count = collections.defaultdict(int)

	domain_comb_to_protein_count = collections.defaultdict(int)
	# MiST domain superfamilies only
	superfamily_comb_to_protein_count = collections.defaultdict(int)

	Genome_id_prev = None
	protein_counter = 0
	with open(INPUT_FILE1, "r") as iFile:
		print("Started analyzing",PROTEIN_TYPE_CHOICES[PROTEIN_TYPE]+"s from the file:", INPUT_FILE1, "\n")
		for protein in iFile:
			# Field 6 has only unique domain names with indicated counts showing how many times a given domain is present in a given protein.
			# Domains are sorted alphabetically
			# Ex., HATPase_c:1,HisKA_2:1,MEDS:1,PAS:1,PAS_3:2,PAS_4:1,PAS_9:1 
			protein_record = protein.strip().split("\t")
			Genome_id = protein_record[0]
			domain_counts = protein_record[9].replace("<", "").replace(">", "")
			# if records of a new genome began, save the previous genome data and update variables
			if Genome_id != Genome_id_prev:
				if Genome_id_prev:
					writeToFile(domain_to_protein_count, Genome_id_prev, OUTPUT_FILE1, DOMAIN_COMB_TYPES["domain"])
					writeToFile(domain_comb_to_protein_count, Genome_id_prev, OUTPUT_FILE2, DOMAIN_COMB_TYPES["domain_comb"])
					writeToFile(superfamily_to_protein_count, Genome_id_prev, OUTPUT_FILE3, DOMAIN_COMB_TYPES["superfamily"])
					writeToFile(superfamily_comb_to_protein_count, Genome_id_prev, OUTPUT_FILE4, DOMAIN_COMB_TYPES["superfamily_comb"])

				Genome_id_prev = Genome_id
				domain_to_protein_count = collections.defaultdict(int)
				domain_comb_to_protein_count = collections.defaultdict(int)
				superfamily_to_protein_count = collections.defaultdict(int)
				superfamily_comb_to_protein_count = collections.defaultdict(int)

			domains_and_counts = domain_counts.split(",")
			# empty list to collect domains of a protein and add the domain combination dictinary (domain_comb_to_protein_count)
			domains = []
			# empty list to collect superfamilie of domains of a proteins and add to the superfamily combination dictionary (superfamily_comb_to_protein_count)
			domains_and_superfamilies = []
			for domain in domains_and_counts:
				domain = domain.split(":")[0]
				# if entry is a sensor domain
				if domain not in HIS_KINASE_DIM_DOMAINS and domain not in HIS_KINASE_CATAL_DOMAINS and domain not in RESPONSE_REG_DOMAINS:
					domain_to_protein_count[domain]+=1
					domains.append(domain)
					if domain in MIST_DOMAIN_TO_SUPERFAMILY:
						superfamily_to_protein_count[MIST_DOMAIN_TO_SUPERFAMILY[domain]]+=1
						domains_and_superfamilies.append(MIST_DOMAIN_TO_SUPERFAMILY[domain])
					else:
						superfamily_to_protein_count[domain]+=1
						domains_and_superfamilies.append(domain)
			# If not sensor domains in HKs or additional domains in RRs:
			if not domains:
				domain = "nodomain"
				domain_to_protein_count[domain]+=1
				domains.append(domain)
				superfamily_to_protein_count[domain]+=1
				domains_and_superfamilies.append(domain)

			# count this domain combination
			domain_comb_to_protein_count[",".join(sorted(domains))]+=1

			# count this superfamily combination
			superfamily_comb_to_protein_count[",".join(sorted(domains_and_superfamilies))]+=1
			
			# Print current info
			protein_counter+=1
			if (protein_counter % 20000 == 0):
				print("Analyzed",  protein_counter, PROTEIN_TYPE_CHOICES[PROTEIN_TYPE]+"s")
		# Print final info
		print("\n******* Analyzed in total",  protein_counter, PROTEIN_TYPE_CHOICES[PROTEIN_TYPE]+"s *******\n")

def writeToFile(dataDict, Genome_id, outputFile, domain_comb_type):
	if Genome_id != "Genome_id" and Genome_id != "Genome_version":
		with open (outputFile, "a") as oFile:
			genome_accession = Genome_id.split(".")[0]
			for element, count in dataDict.items():
				normed_bysize = float(count)/GENOME_TO_SIZE[Genome_id][0]
				normed_byprotcount = float(count)/GENOME_TO_SIZE[Genome_id][1]
				oFile.write("\t".join([Genome_id, genome_accession, SOURCE, PROTEIN_TYPE, element, domain_comb_type, str(count), str(normed_bysize), str(normed_byprotcount)]) + "\n")

def main(argv):
	initialize(argv)
	processInput()
	findDomainAndCombPrevalenceInProteins()

main(sys.argv)
