#!/usr/bin/python3
import sys, getopt
import collections
import re

USAGE = "\nThe script calculates domain and domain combination prevalences at chosen taxonomy levels using the result of the 'analyze_tcs_per_genome' script. \n" + \
	"'analyze_tcs_per_genome' script produces domain (as well as domain combination, domain superfamily, domain superfamily combination) count statisitcs per genome.\n\n" + \
	"python " + sys.argv[0] + '''
	-h || --help               - help
	-d || --dsource            - source database: mistdb (MiST; default) or rmodels (Pfam HMMs with relaxed thresholds) 
	-p || --ptype              - protein type: hk (histidine kinase), rr (reponse regulator), ocp (one-component protein)
	-c || --ctype              - domain combiantion type: domain (single domain), domain_comb (a string of domains), 
								 superfamily (single domain superfamily that may represent many domains), superfamily_comb (a string of superfamilies)
	-i || --ifile              - input file 1 (protein and domain statistics information file generated by the analyze_tcs_pergenome.py script, one of four:
	                                * domain prevalence
							        * domain combination prevalence
							        * domain supefamily prevalence
							        * domain supefamily combination prevalence)
	-s || --sfile              - input file 2 (GTDB taxonomy metadata file)
	-f || --ffile              - output file 1 (protein and domains statistics per selected taxon)
	-t || --taxlevel           - taxonomy level to calculate the average at (one of "species", "genus", "order", "family", "class", "phylum", "kingdom")
'''
# Variables controlled by the script parameters
SOURCE = "mistdb"
SOURCE_CHOICES = {"mistdb", "rmodels"}
PROTEIN_TYPE = "hk"
PROTEIN_TYPE_CHOICES = {"hk", "rr", "ocp"}
DOMAIN_COMB_TYPE = "domain"
DOMAIN_COMB_TYPE_CHOISES = {"domain", "domain_comb", "superfamily", "superfamily_comb"}

INPUT_FILE1 = None
INPUT_FILE2 = None
TAXONOMY_LEVEL = 7
TAXONOMY_LEVEL_STR = "species"

OUTPUT_FILE1 = "domain_statistics_per_taxon.tsv"

GENOME_TO_DOMAIN = collections.defaultdict(list)
GENOME_TO_TAXONOMY = {}
# {"full taxonomy up to the selected level": ["Genome1", "Genome2", "Genome3", ...], ...}
TAXONOMY_TO_GENOMES = collections.defaultdict(list)

# {"full taxonomy up to the selected level": {"domain1 (domain combination 1)": 21, "domain2(or domain comb 2)": 852, ...}, ...}
# {"full taxonomy up to the selected level": {"domain1 (domain comb 1)": 
# {"raw_count":2, "raw_normto_genomenum":0.002, "normby_genomesize_normto_genomenum":0.025, 
#  "normby_protcount_normto_genomenum": 0.00005}, "domain2(or domain comb 2)": {...}, ...}, ...}
TAXONOMY_TO_STATISTICS = collections.defaultdict(dict)

def initialize(argv):
	global INPUT_FILE1, INPUT_FILE2, OUTPUT_FILE1, TAXONOMY_LEVEL, SOURCE, PROTEIN_TYPE, DOMAIN_COMB_TYPE, TAXONOMY_LEVEL_STR
	try:
		opts, args = getopt.getopt(argv[1:],"hd:p:c:i:s:f:t:",["help", "dsource=", "ptype=", "ctype=", "ifile=", "sfile=", "ffile=", "taxlevel="])
		if len(opts) == 0:
			raise getopt.GetoptError("Options are required\n")
	except getopt.GetoptError as e:
		print("===========ERROR==========\n " + str(e) + USAGE)
		sys.exit(2)
	try:
		for opt, arg in opts:
			if opt in ("-h", "--help"):
				print(USAGE)
				sys.exit()
			elif opt in ("-d", "--dsource"):
				if str(arg).strip() in SOURCE_CHOICES:
					SOURCE = str(arg).strip()
			elif opt in ("-p", "--ptype"):
				if str(arg).strip() in PROTEIN_TYPE_CHOICES:
					PROTEIN_TYPE = str(arg).strip()
			elif opt in ("-c", "--ctype"):
				if str(arg).strip() in DOMAIN_COMB_TYPE_CHOISES:
					DOMAIN_COMB_TYPE = str(arg).strip()
			elif opt in ("-i", "--ifile"):
				INPUT_FILE1 = str(arg).strip()
			elif opt in ("-s", "--sfile"):
				INPUT_FILE2 = str(arg).strip()
			elif opt in ("-f", "--ffile"):
				OUTPUT_FILE1 = str(arg).strip()
			elif opt in ("-t", "--taxlevel"):
				TAXONOMY_LEVEL_STR = str(arg).strip()
				TAXONOMY_LEVEL = tax_level_selector(TAXONOMY_LEVEL_STR)
				print("Taxonomy level is '" + TAXONOMY_LEVEL_STR + "':", TAXONOMY_LEVEL)
				if TAXONOMY_LEVEL == None:
					raise IOError("Incorrect argument of -t (--taxlevel) option")
	except Exception as e:
		print("===========ERROR==========\n" + str(e) + USAGE)
		sys.exit(2)

def process_input():
	# regex to remove prefix .__ (like d__, p__, etc. from the GTDB taxonomomy string)
	regex=r'.__'
	with open(INPUT_FILE1, "r") as iFile1:
		for line in iFile1:
			# domain_c can be a signle domain (GAF_3) or a domain combination (ex, GAF_3,PAS_3,PAS_4,hole)
			linesplt = line.strip().split("\t")
			genomeID = linesplt[0]
			domain_c = linesplt[4]
			count = linesplt[6] 
			normby_genomesize = linesplt[7]
			normby_protcount = linesplt[8]
			# {"GenomeID1": (TIM, 5), ... }
			# Can be domain combination to counts: ("TIM,PIR", 62), ...
			# int(count) below is repeated to make the analysis in the process_domains_per_taxon() function
			# straightforward
			GENOME_TO_DOMAIN[genomeID].append((domain_c, int(count), int(count), float(normby_genomesize), float(normby_protcount)))
	with open(INPUT_FILE2, "r") as iFile2:
		for line in iFile2:
			record = line.strip().split("\t")
			genomeID = "_".join(record[0].split("_")[1:])
			taxonomy = ";".join(record[2].split(";")[:TAXONOMY_LEVEL])
			taxonomy = re.sub(regex, "", taxonomy)
			GENOME_TO_TAXONOMY[genomeID] = taxonomy
			TAXONOMY_TO_GENOMES[taxonomy].append(genomeID)

# reports inofrmation per taxon
# G1 Domcomb2 12
# d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanosarcina;s__Methanosarcina mazei
def process_domains_per_taxon():
	counts = collections.OrderedDict({"raw_count":0, "raw_normto_genomenum":0, "normby_genomesize_normto_genomenum":0, "normby_protcount_normto_genomenum": 0})
	counter = 1
	for genomeID, domain_counts in GENOME_TO_DOMAIN.items():
		for element in domain_counts:
			taxon = GENOME_TO_TAXONOMY[genomeID]
			domain_c = element[0]
			if  domain_c in TAXONOMY_TO_STATISTICS[taxon]:
				for index, count_type in enumerate(counts.keys()):
					TAXONOMY_TO_STATISTICS[taxon][domain_c][count_type] += element[index+1]
			else:
				TAXONOMY_TO_STATISTICS[taxon][domain_c] = counts.copy()
				for index, count_type in enumerate(counts.keys()):
					TAXONOMY_TO_STATISTICS[taxon][domain_c][count_type] = element[index+1]

def normalize_counts_and_save():
	with open(OUTPUT_FILE1, "w") as oFile:
		for taxon, domain_dict in TAXONOMY_TO_STATISTICS.items():
			numOfGenomesInTaxon = len(TAXONOMY_TO_GENOMES[taxon])
			taxon_last = taxon.split(";")[-1]
			for domain_c, count_dict in domain_dict.items():
				counts_list = []
				for count_type in count_dict.keys():
					if not count_type == "raw_count":
						count_dict[count_type] = count_dict[count_type]/float(numOfGenomesInTaxon)
					counts_list.append(str(count_dict[count_type]))
				oFile.write("\t".join([taxon, taxon_last, TAXONOMY_LEVEL_STR, SOURCE, PROTEIN_TYPE, domain_c, DOMAIN_COMB_TYPE, "\t".join(counts_list)]) + "\n")

def tax_level_selector(level):
	if level == "species":
		return 7
	elif level == "genus":
		return 6
	elif level == "family":
		return 5
	elif level == "order":
		return 4
	elif level == "class":
		return 3
	elif level == "phylum":
		return 2
	elif level == "kingdom":
		return 1
	return None
						
def main(argv):
	initialize(argv)
	process_input()
	process_domains_per_taxon()
	normalize_counts_and_save()

main(sys.argv)
